### ISSUE TITLE
Incompatible with Firefly III v6.5.1

### ISSUE THREAD

**Issue by RedPine404** [dreautall/waterfly-iii#751]
After upgrading the Firefly III server from v6.5.0 to v6.5.1 authentication results in the following error:

```
Unknown error.

Host: https://<my.server.tld>

NoSuchMethodError: The method '[]' was called on

null.

Receiver: null

Tried calling: []("title")
```

Rolling back to v6.5.0 for now without issues.

Waterfly III version is android 1.2.0-beta.2.

The release notes for v6.5.1 state changes to the /api/v1/users API endpoint.

**Comment by dreautall** [comment]
Seems like a Firefly III issue, created a bug report: https://github.com/firefly-iii/firefly-iii/issues/11842

**Comment by dreautall** [comment]
Should be fixed next FF3 release. I'll keep this issue open until the update is out in case people stumble upon the same error, thank you for reporting!

**Comment by RedPine404** [comment]
I see it was added to the Firefly III v6.5.2 milestone. Thank you for your work! I use your software every day. Not having to manually input everything I buy is so helpful!

**Comment by JC5** [comment]
My apologies everybody, I was a little overzealous fixing a security issue. The new release will come out within the hour.

**Comment by dreautall** [comment]
Thank you for the fix and the hard work on FF3! ❤️
